### ISSUE TITLE
"Controle de versão com git: Bruna, Victor e Douglas - Turma 1"

### ISSUE THREAD

**Issue by victorcardozo** [mat-esp-2016/intro-git-bvd#1]
https://github.com/mat-esp-2016/intro-git-bvd

A maioria dos problemas encontrados foram comentados juntos a cada commit.
Tivemos apenas um problema não comentado nos commits que foi a inclusão do repositório remoto do GitHub. Acabamos adicionando uma URL errada.
Pesquisando, descobrimos que para remover esse repositório, precisaríamos utilizar o comando git remote remove origin e então adicionar o repositório correto.

**Comment by leouieda** [comment]
Vocês criaram a issue no lugar errado. Leiam: https://github.com/mat-esp-2016/intro-git-bvd#entrega-das-solu%C3%A7%C3%B5es

**Comment by dgmilanez** [comment]
Corrigido professor!
Pedimos desculpas pelo engano.
Muito obrigado!

**Comment by leouieda** [comment]
OK, recebido.
